### ISSUE TITLE
Is this plugin still maintained?

### ISSUE THREAD

**Issue by alokjkumar** [MCanhisares/twilio-ios-capacitor#2]
Is this plugin still being maintained? I tried to use it but with no success.

**Comment by wmehanna** [comment]
> Is this plugin still being maintained? I tried to use it but with no success.

I about to use this plugin.  Any success with it ? Anything I should know about ?

**Comment by TravBradfield** [comment]
I'm not convinced that this plugin works... 

@alokjkumar and @wmehanna have you had any success? Please share your experience! Thanks

**Comment by alokjkumar** [comment]
I never got it working - Cordova plugin works fine for ionic though

https://github.com/okode/cordova-plugin-twilio-video

**Comment by TravBradfield** [comment]
@alokjkumar Thank you!
